In [1]:
import numpy as np
import pandas as pd
import torch

In [2]:
data = [
    [0.9, 0.6, 0.3, 0, -0.9],
    [0.8, 0.5, 0.1, -0.3, -0.8],
    [0.8, 0.6, 0.2, -0.5, -0.6],
    [0.9, 0.7, 0.4, 0, -0.7],
    [0.8, 0.5, 0.2, 0.1, -0.8],
    [0.9, 0.6, 0.3, 0.2, -0.8]
]
df = pd.DataFrame(data)

X, y = torch.tensor(np.array(df.iloc[:-1])), torch.tensor(np.array(df.iloc[-1]))
X

tensor([[ 0.9000,  0.6000,  0.3000,  0.0000, -0.9000],
        [ 0.8000,  0.5000,  0.1000, -0.3000, -0.8000],
        [ 0.8000,  0.6000,  0.2000, -0.5000, -0.6000],
        [ 0.9000,  0.7000,  0.4000,  0.0000, -0.7000],
        [ 0.8000,  0.5000,  0.2000,  0.1000, -0.8000]], dtype=torch.float64)

In [3]:
y

tensor([ 0.9000,  0.6000,  0.3000,  0.2000, -0.8000], dtype=torch.float64)

In [4]:
past_weights = torch.tensor(np.array([0.2, 0.2, 0.2, 0.2, 0.2]))

pred_weights = torch.tensor(np.array([0.1, 0.1, 0.2, 0.3, 0.3]))
pred_weights

tensor([0.1000, 0.1000, 0.2000, 0.3000, 0.3000], dtype=torch.float64)

In [9]:
def sharpe(y, pred_weights, 
           X, past_weights):
    weighted_returns = torch.mul(y, pred_weights)

    weighted_past_returns = torch.mul(X, past_weights)

    adjusted_returns = 1 + weighted_past_returns
    cumulative = torch.prod(adjusted_returns, dim=0)

    total = (cumulative * (weighted_returns + 1)) - 1

    all_returns = torch.cat((weighted_past_returns, weighted_returns.unsqueeze(0)), 0)

    return weighted_returns, weighted_past_returns, cumulative, total, all_returns

In [10]:
a, b, c, d, e = sharpe(y, pred_weights, X, past_weights)
sharpe(y, pred_weights, X, past_weights)

(tensor([ 0.0900,  0.0600,  0.0600,  0.0600, -0.2400], dtype=torch.float64),
 tensor([[ 0.1800,  0.1200,  0.0600,  0.0000, -0.1800],
         [ 0.1600,  0.1000,  0.0200, -0.0600, -0.1600],
         [ 0.1600,  0.1200,  0.0400, -0.1000, -0.1200],
         [ 0.1800,  0.1400,  0.0800,  0.0000, -0.1400],
         [ 0.1600,  0.1000,  0.0400,  0.0200, -0.1600]], dtype=torch.float64),
 tensor([2.1734, 1.7303, 1.2630, 0.8629, 0.4379], dtype=torch.float64),
 tensor([ 1.3690,  0.8341,  0.3388, -0.0853, -0.6672], dtype=torch.float64),
 tensor([[ 0.1800,  0.1200,  0.0600,  0.0000, -0.1800],
         [ 0.1600,  0.1000,  0.0200, -0.0600, -0.1600],
         [ 0.1600,  0.1200,  0.0400, -0.1000, -0.1200],
         [ 0.1800,  0.1400,  0.0800,  0.0000, -0.1400],
         [ 0.1600,  0.1000,  0.0400,  0.0200, -0.1600],
         [ 0.0900,  0.0600,  0.0600,  0.0600, -0.2400]], dtype=torch.float64))

In [7]:
torch.squeeze(x)

NameError: name 'x' is not defined